### ISSUE TITLE
OSR forum bug #3

### ISSUE THREAD

**Issue by thememers** [climu/openstudyroom#280] opened 2018-08-04 05:49 UTC
There is no option anywhere on the page to delete your own forum posts. I would say this is fine as it is probably a deliberate choice but currently updating posts to add attachments is bugged so being able to delete and repost a forum thread would be a temporary fix.

**Comment by climu** [comment] 2018-10-28 23:51
This is a setting: only mods can delete posts. 

It can be discussed but it's not a bug so I am closing that.

For the record, people can now update their posts.

**Closed by climu** 2018-10-28 23:51 UTC
