### ISSUE TITLE
calendar problem for Android

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#199] opened 2017-10-16 11:11 UTC
![screenshot_20171016-075251](https://user-images.githubusercontent.com/27974470/31609093-287783ac-b249-11e7-946b-5a709b6f9db6.png)

Climu

There is a yellow rectangle covering up today, which does not let me add availability.  The aujourdhui button does not seem to do anything.  See attached screenshot.  

Kind regards

Alex Mitrani

**Comment by climu** [comment] 2017-10-17 05:16
Hey,

thanks for spotting that.

I think this is the left bar with the 'menu' that overflow the calendar.

I willl be working on supporting smalls screen better.

**Comment by alexmitrani** [comment] 2017-10-17 11:41
thanks climu.  the left menu does overflow the calendar, but I don't think
it is only that.  the yellow fill on "today" impedes defining availability,
or it hides it - I'm not sure which.  What I noticed is that when I try to
define availability for today, it looks like nothing happens.

Thanks again for looking into it.

Alex

**Comment by climu** [comment] 2017-10-17 15:47
Sure :)

I can't reproduce the issue that we canot select today's availability on my computer. Maybe it's only on touched device.

I did a [small update](https://github.com/climu/openstudyroom/pull/200/commits/ba92c4efc7db05d45056e911652d8c087ae16d60) on css/html so it should be better on small devices.

Feel free to let me know if it's any better.

**Comment by climu** [comment] 2017-11-07 00:34
I had feedback on discord that it is better.

I am well aware that our all website is not really mobile friendly.

Since I believe this issue doesn't really affect the use of the calendar anymore, I will close it.

**Closed by climu** 2017-11-07 00:34 UTC
Labels: bug, easy, high priority
