### ISSUE TITLE
SGFs not being accepted for 1k tournament

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#366] opened 2019-03-09 16:12 UTC
The error message is "not a match".  
Here is an example of the type of SGF not being accepted: 

[16916870-207-alemitrani-BoneSaw.txt](https://github.com/climu/openstudyroom/files/2948566/16916870-207-alemitrani-BoneSaw.txt)

**Comment by climu** [comment] 2019-03-09 22:57
This is because the game was forfeited. So the website doesn't consider it as a match to be played.

After unforfeiting the match I have no issue.

![image](https://user-images.githubusercontent.com/2648653/54078355-f9001200-42c6-11e9-84af-de1b9ad3f52b.png)

**Comment by climu** [comment] 2019-03-09 23:06
Kamelo is getting different issue. I think it's related to permission...

**Comment by climu** [comment] 2019-03-26 15:09
I don't understand the issue and canot manage to reproduce.

Without more details like reproduction steps I cannot fit that.

**Comment by climu** [comment] 2019-10-18 11:59
Closing for now cause I am not even sure there is a bug.

**Closed by climu** 2019-10-18 11:59 UTC
Labels: bug, need more infos
