### ISSUE TITLE
Report issue to admins when "Game Analysis" is enabled

### ISSUE THREAD

**Issue by d-korni** [climu/openstudyroom#348] opened 2019-01-15 09:26 UTC
Recently in e8c61a1 we added a check if "Game Analysis" is enabled.
This leads to the SGF not being picked up by the scrapper and thus not to appear in SGFs for the admins.

I think it would be useful if it does get picked up but the marked as "League Invalid: Analysis Enabled" so admins can quickly give feedback to users.

**Comment by climu** [comment] 2019-03-02 10:55
Hum, I am not sure about that actually.

Keeping invalid sgf in our database is not really ideal. We do that only because KGS doesn't have an API:
1) we download sgf with matching players.
2) we check validity
3) we keep the sgf anyhow to prevent downloading it again.

But with the API we have informations without downloading the sgf and I am not sure we want to download and store those invalid sgf.

**Comment by d-korni** [comment] 2019-03-07 00:03
How about we have a checker utility, where the users can post the link to a specific SGF and then understand why it was not valid. This way, users can check their own games and save time from admins and the files don't have to be stored in our server. We would have to just improve the feedback given by the said checker utility. Essentially we already have this, just need to make a public version of it with a face-lift. ^^

**Comment by climu** [comment] 2019-03-07 08:13
That is a good idea!

The issue is the game-analysis information is not in the sgf but in the OGS API. We could add a field for use to put the OGS url of the game and we would get information from the API. As usual, PR welcome :)

**Comment by d-korni** [comment] 2019-03-07 08:15
The idea would be to check everything, so yes, they provide OGS/KGS url and we process all the data for the relevant outputs. Even if we have to store locally the SGF, we delete it once done with it.

Unlikely that I will be able to work on the website side. :/

**Comment by climu** [comment] 2019-03-07 08:30
Sure, I wasn't pushing for you to work on that. Let say it's not a high priority feature for now.

**Comment by climu** [comment] 2019-03-07 08:33
Hum, I think we should close this and open a new "allow users to manually check their games validity" issue.

**Closed** 2019-03-26 15:39 UTC
Labels: enhancement, help wanted, medium priority
